# Generated by Django 6.0.6 on 2026-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('suv', 'SUV'), ('caminhonete', 'Caminhonete')], max_length=20)),
                ('vaga', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('estacionamento', 'Estacionamento'), ('reservadod', 'Reservado'), ('saida_prevista', 'Saida prevista')], default='estacionado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
