# Generated by Django 6.0.6 on 2026-06-19 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_placa', message='Informe uma placa válida no padrão Mercosul, como ABC1D23.', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$')]),
        ),
    ]
