# Generated by Django 6.0.6 on 2026-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('estacionando', 'Estacionando'), ('reservado', 'Reservado'), ('saida_prevista', 'Saida prevista')], default='estacionado', max_length=20),
        ),
    ]
