# Generated by Django 6.0.6 on 2026-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='criado_em',
            new_name='entrada_em',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='saida_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('estacionado', 'Estacionado'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado')], default='estacionado', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vaga',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
