# Generated by Django 6.0.6 on 2026-07-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
        ('veiculos', '0004_rename_criado_em_veiculo_entrada_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='entrada_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='saida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('estacionado', 'Estacionado'), ('finalizado', 'Finalizado')], default='estacionado', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='vagas.vaga'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
