# Generated by Django 6.0.6 on 2026-07-04 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
        ('veiculos', '0005_remove_veiculo_tipo_alter_veiculo_entrada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='entrada_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('estacionado', 'Estacionado'), ('reservado', 'Reservado'), ('finalizado', 'Finalizado')], default='estacionado', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.vaga'),
        ),
    ]
